In [1000]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [1001]:
df = pd.read_csv("./penguins_size.csv")

In [1002]:
df.head()

species     island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen              39.1             18.7              181.0   
1  Adelie  Torgersen              39.5             17.4              186.0   
2  Adelie  Torgersen              40.3             18.0              195.0   
3  Adelie  Torgersen               NaN              NaN                NaN   
4  Adelie  Torgersen              36.7             19.3              193.0   

   body_mass_g     sex  
0       3750.0    MALE  
1       3800.0  FEMALE  
2       3250.0  FEMALE  
3          NaN     NaN  
4       3450.0  FEMALE

In [1003]:
df.describe()

culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g
count        342.000000       342.000000         342.000000   342.000000
mean          43.921930        17.151170         200.915205  4201.754386
std            5.459584         1.974793          14.061714   801.954536
min           32.100000        13.100000         172.000000  2700.000000
25%           39.225000        15.600000         190.000000  3550.000000
50%           44.450000        17.300000         197.000000  4050.000000
75%           48.500000        18.700000         213.000000  4750.000000
max           59.600000        21.500000         231.000000  6300.000000

In [1004]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   culmen_length_mm   342 non-null    float64
 3   culmen_depth_mm    342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                334 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [1005]:
cols = df.columns
df = df.sample(frac=1)

In [1006]:
df = df.dropna()

In [1007]:
df["species"].value_counts()

species
Adelie       146
Gentoo       120
Chinstrap     68
Name: count, dtype: int64

In [1008]:
df = df[df["sex"] != '.']
df["sex"].value_counts()

sex
MALE      168
FEMALE    165
Name: count, dtype: int64

In [1009]:
df["species"] = df["species"].map({"Adelie" : 0, "Gentoo" : 1, "Chinstrap" : 2})
df["island"] = df["island"].map({"Biscoe" : 0, "Dream" : 1, "Torgersen" : 2})
df["sex"] = df["sex"].map({"MALE" : 0, "FEMALE" : 1})

'\ndf["species"] = df["species"].map({"Adelie" : 0, "Gentoo" : 1, "Chinstrap" : 2})        # todo : Use Encoder\ndf["island"] = df["island"].map({"Biscoe" : 0, "Dream" : 1, "Torgersen" : 2})           # todo : Use Encoder\ndf["sex"] = df["sex"].map({"MALE" : 0, "FEMALE" : 1})\n'

In [ ]:
cols = ['island', 'culmen_length_mm', 'culmen_depth_mm', 'flipper_length_mm', 'body_mass_g', 'sex']
X = df[cols]
y = df["species"]

## Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(266, 6) (67, 6)
(266,) (67,)


## Scaling

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train_s = scaler.fit_transform(X_train)

In [ ]:
y_train = y_train.values
y_train

array([2, 1, 2, 0, 0, 1, 2, 0, 0, 2, 0, 2, 1, 1, 0, 1, 2, 0, 1, 1, 0, 0,
       0, 2, 0, 1, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 2, 2, 0, 2, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 2, 1, 0, 0, 1, 0, 2, 1, 2, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 2, 1, 0, 0, 0, 1, 1, 1, 2, 2, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 2, 2, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 2, 0, 0, 2, 0, 2, 1, 0, 1, 1, 1, 2, 0, 2, 2, 1, 1, 0, 0,
       1, 0, 0, 2, 0, 2, 0, 0, 0, 1, 0, 1, 0, 2, 0, 0, 1, 2, 2, 2, 2, 1,
       1, 0, 1, 0, 2, 2, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 2, 0, 1, 0, 1, 0, 1, 2, 2, 2, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       2, 1, 0, 2, 0, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 1, 0, 2, 1, 2, 0, 1,
       2, 2, 0, 0, 0, 2, 1, 0, 0, 0, 0, 2, 1, 2, 1, 0, 0, 1, 0, 0, 1, 0,
       2, 0], dtype=int64)

## Training

In [ ]:
from sklearn.svm import SVC

def trainer(data, label):
    clf = SVC(random_state=42, C=1, degree=2, gamma=0.1, kernel="rbf")
    return clf.fit(data, label)

In [ ]:
svc_clf = trainer(X_train_s, y_train)

## Pred

In [ ]:
X_test_s = scaler.fit_transform(X_test)

In [ ]:
y_pred = svc_clf.predict(X_test_s)
y_pred

array([2, 1, 0, 2, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 2,
       0, 2, 1, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 2, 2, 2,
       1, 0, 1, 1, 1, 1, 2, 0, 1, 0, 2, 0, 0, 1, 0, 1, 0, 1, 2, 0, 1, 0,
       0], dtype=int64)

In [ ]:
y_test = y_test.values
y_test

array([2, 1, 0, 2, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 2,
       0, 2, 1, 0, 0, 0, 2, 1, 2, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 2, 2, 2,
       1, 0, 1, 1, 1, 1, 2, 0, 1, 0, 2, 0, 0, 1, 0, 1, 0, 1, 2, 0, 1, 0,
       0], dtype=int64)

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.9850746268656716
